# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class O2 < Formula
  desc "OpenObserve CLI - Manage OpenObserve resources from command line"
  homepage "https://github.com/openobserve/o2-cli"
  version "1.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openobserve/o2-cli/releases/download/v1.2.1/o2-darwin-amd64.tar.gz"
      sha256 "4b661c800dd362c0ea2dc443a080f912fa47e6a62c0729e29941cda403b34bc5"

      define_method(:install) do
        bin.install "o2"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openobserve/o2-cli/releases/download/v1.2.1/o2-darwin-arm64.tar.gz"
      sha256 "a6cbb4ffc0193b8378775acf32f833529c0002de1055d7c9ac39b38781ef2938"

      define_method(:install) do
        bin.install "o2"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openobserve/o2-cli/releases/download/v1.2.1/o2-linux-amd64.tar.gz"
      sha256 "62db682f52ee56fb246c80199aebdaa914e8b1de1c630e09e20f8fcba85c06cb"
      define_method(:install) do
        bin.install "o2"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openobserve/o2-cli/releases/download/v1.2.1/o2-linux-arm64.tar.gz"
      sha256 "87980eca0e0325fea5719d62165f7262551be68a68ac97dff9971824ea34fe99"
      define_method(:install) do
        bin.install "o2"
      end
    end
  end

  test do
    system "#{bin}/o2", "--version"
  end
end
