# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class O2 < Formula
  desc "OpenObserve CLI - Manage OpenObserve resources from command line"
  homepage "https://github.com/openobserve/o2-cli"
  version "1.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openobserve/o2-cli/releases/download/v1.2.0/o2-darwin-amd64.tar.gz"
      sha256 "558b73eb0b40e4e40ba0f4ef9832b24713df9bf6ff08207b41a72580dac1ecd6"

      define_method(:install) do
        bin.install "o2"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openobserve/o2-cli/releases/download/v1.2.0/o2-darwin-arm64.tar.gz"
      sha256 "386eea02a54c6605a2f6ea44fd877b774f73aa8695c7317ddf6bb550ad636179"

      define_method(:install) do
        bin.install "o2"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openobserve/o2-cli/releases/download/v1.2.0/o2-linux-amd64.tar.gz"
      sha256 "5a293b523a5d1dfdfc786ba200609f64119297f07236ed5a1e19c4b685350ff5"
      define_method(:install) do
        bin.install "o2"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openobserve/o2-cli/releases/download/v1.2.0/o2-linux-arm64.tar.gz"
      sha256 "399205ea470a14db66bd9961825d8a34d0d85cd0bb87ea55119eb1dd0fcd6654"
      define_method(:install) do
        bin.install "o2"
      end
    end
  end

  test do
    system "#{bin}/o2", "--version"
  end
end
