# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class O2 < Formula
  desc "OpenObserve CLI - Manage OpenObserve resources from command line"
  homepage "https://github.com/openobserve/o2-cli"
  version "1.1.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/openobserve/o2-cli/releases/download/v1.1.3/o2-darwin-amd64.tar.gz"
      sha256 "eae64d460764ca39c992bca3d01846c5a701b51a0756a00d31948d07bd6fe13d"

      def install
        bin.install "o2"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/openobserve/o2-cli/releases/download/v1.1.3/o2-darwin-arm64.tar.gz"
      sha256 "2c5f971281f877777fd5e78db53fe0af26bc3e8f2f923eb8f9d4d77e44bf609a"

      def install
        bin.install "o2"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/openobserve/o2-cli/releases/download/v1.1.3/o2-linux-amd64.tar.gz"
      sha256 "5cfea39a7b54e2011d930a6bcbf462e1636edaf3eb5760737b4e887a2ffbee68"
      def install
        bin.install "o2"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/openobserve/o2-cli/releases/download/v1.1.3/o2-linux-arm64.tar.gz"
      sha256 "a9bf5ff348cd259c88f1cf0a31810b2dc846f5ae7083f3f061152957140a7f4d"
      def install
        bin.install "o2"
      end
    end
  end

  test do
    system "#{bin}/o2", "--version"
  end
end
