# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zinc < Formula
  desc "Zinc is a search engine that does full text indexing. It is a lightweight
alternative to elasticsearch that requires significantly less resources. It uses
bluge as the underlying indexing library.

It is very simple and easy to operate as opposed to elasticsearch which
requires a couple dozen knobs to understand and tune.

It is a drop-in replacement for elasticsearch if you are just ingesting
data using APIs and searching using kibana (Kibana is not supported with
zinc. Zinc provides its own UI).
"
  homepage "https://github.com/zinclabs/zinc"
  version "0.1.9"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zinclabs/zinc/releases/download/v0.1.9/zinc_0.1.9_Darwin_arm64.tar.gz"
      sha256 "3d62e73cf40ce7398f86690f20e176397d9a62941f26dcc634eb1fd2e7e0b6a6"

      def install
        bin.install "zinc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zinclabs/zinc/releases/download/v0.1.9/zinc_0.1.9_Darwin_x86_64.tar.gz"
      sha256 "cee3afa3a9dc0810d7725a0a3808fdf8fd0544642111fa5ac5c1d0efcd51b739"

      def install
        bin.install "zinc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/zinclabs/zinc/releases/download/v0.1.9/zinc_0.1.9_Linux_armv6.tar.gz"
      sha256 "b3de5a452dd88aa18fad87ecc2bc94838805ea83263bf8e506afbb914bfc7cb6"

      def install
        bin.install "zinc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zinclabs/zinc/releases/download/v0.1.9/zinc_0.1.9_Linux_arm64.tar.gz"
      sha256 "eac8c607e07af377b20c9c0724f57ec33f308ec7c64627d7b2c6674a11aa9891"

      def install
        bin.install "zinc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zinclabs/zinc/releases/download/v0.1.9/zinc_0.1.9_Linux_x86_64.tar.gz"
      sha256 "126385d1b438dda817aa91989caf02d4caa9e96c99b3dae54c367ebbed19d356"

      def install
        bin.install "zinc"
      end
    end
  end
end
